name: Deploy to HostingKR

on:
  push:
    branches: [main] # main 브랜치에 푸시될 때 실행

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: yarn install

      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_HOST }} # ex) hlwemqth.hostingkr.com
          username: ${{ secrets.FTP_USER }} # FTP 아이디
          password: ${{ secrets.FTP_PASSWORD }} # FTP 비밀번호
          protocol: ftps-legacy
          port: 21
          local-dir: ./
          server-dir: public_html/ # 호스팅KR 웹 루트 경로
          timeout: 60000
